string_objs=\
$(string_dir)\memcmp.o\
$(string_dir)\memcpy.o\
$(string_dir)\memmove.o\
$(string_dir)\memset.o\
$(string_dir)\memsetw.o\
$(string_dir)\strcat.o\
$(string_dir)\strcmp.o\
$(string_dir)\strcpy.o\
$(string_dir)\strdup.o\
$(string_dir)\strext.o\
$(string_dir)\strlen.o\
$(string_dir)\substr.o